=== PiTi2k5/Obelisk/data/wiki/.schema/drops.json
{
	"title": "Dino drop loot tables",
	"type": "object",
	"properties": {
		"version": {
			"title": "Version",
			"description": "Data version of the format <gamemajor>.<gamemajor>.<specificversion>, e.g. '306.83.4740398'",
			"type": "string"
		},
		"format": {
			"title": "Format",
			"description": "Free-form format identifier, changed only when incompatibilities are introduced",
			"type": "string"
		},
		"mod": {
			"title": "Mod info",
			"description": "Source module information",
			"allOf": [
				{
					"$ref": "#/definitions/ModInfo"
				}
			]
		},
		"drops": {
			"title": "Drops",
			"description": "List of loot crates",
			"type": "array",
			"items": {
				"$ref": "#/definitions/Drop"
			}
		}
	},
	"required": [
		"version",
		"format",
		"drops"
	],
	"additionalProperties": false,
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"ModInfo": {
			"title": "ModInfo",
			"type": "object",
			"properties": {
				"id": {
					"title": "Mod ID",
					"type": "string"
				},
				"tag": {
					"title": "Blueprint tag",
					"description": "Used in place of the mod ID in blueprint paths",
					"type": "string"
				},
				"title": {
					"title": "Mod name",
					"type": "string"
				}
			},
			"required": [
				"id",
				"tag",
				"title"
			]
		},
		"MinMaxPowerRange": {
			"title": "MinMaxPowerRange",
			"type": "object",
			"properties": {
				"min": {
					"title": "Min",
					"anyOf": [
						{
							"type": "number"
						},
						{
							"type": "integer"
						},
						{
							"type": "number"
						}
					]
				},
				"max": {
					"title": "Max",
					"anyOf": [
						{
							"type": "number"
						},
						{
							"type": "integer"
						},
						{
							"type": "number"
						}
					]
				},
				"pow": {
					"title": "Power",
					"description": "Affects the power curve used to select a value in the range",
					"anyOf": [
						{
							"type": "number"
						},
						{
							"type": "integer"
						},
						{
							"type": "number"
						}
					]
				}
			},
			"required": [
				"min",
				"max",
				"pow"
			],
			"additionalProperties": false
		},
		"ItemSetEntry": {
			"title": "ItemSetEntry",
			"type": "object",
			"properties": {
				"name": {
					"title": "Name",
					"type": "string"
				},
				"weight": {
					"title": "Weight",
					"type": "number"
				},
				"qty": {
					"$ref": "#/definitions/MinMaxPowerRange"
				},
				"quality": {
					"$ref": "#/definitions/MinMaxPowerRange"
				},
				"forceBP": {
					"title": "Forcebp",
					"type": "boolean"
				},
				"items": {
					"title": "Items",
					"type": "array",
					"items": {
						"type": "string"
					}
				}
			},
			"required": [
				"weight",
				"qty",
				"quality",
				"forceBP",
				"items"
			],
			"additionalProperties": false
		},
		"ItemSet": {
			"title": "ItemSet",
			"type": "object",
			"properties": {
				"name": {
					"title": "Name",
					"type": "string"
				},
				"weight": {
					"title": "Weight",
					"anyOf": [
						{
							"type": "number"
						},
						{
							"type": "number"
						}
					]
				},
				"qtyScale": {
					"$ref": "#/definitions/MinMaxPowerRange"
				},
				"entries": {
					"title": "Entries",
					"type": "array",
					"items": {
						"$ref": "#/definitions/ItemSetEntry"
					}
				}
			},
			"required": [
				"weight",
				"qtyScale",
				"entries"
			],
			"additionalProperties": false
		},
		"Drop": {
			"title": "Drop",
			"type": "object",
			"properties": {
				"bp": {
					"title": "Bp",
					"description": "Full blueprint path",
					"type": "string"
				},
				"sets": {
					"title": "Sets",
					"description": "Loot sets",
					"type": "array",
					"items": {
						"$ref": "#/definitions/ItemSet"
					}
				}
			},
			"required": [
				"bp"
			],
			"additionalProperties": false
		}
	}
}

=== PiTi2k5/Obelisk/data/wiki/899987403-Primal_Fear_Bosses/drops.json
{
	"$schema": "../.schema/drops.json",
	"version": "310.90.1570545692",
	"format": "3",
	"mod": {
		"id": "899987403",
		"tag": "Primal_Fear_Bosses",
		"title": "Primal Fear Bosses"
	},
	"drops": [
		{
			"bp": "/Game/Mods/Primal_Fear_Bosses/LootSets/Alpha/DinoDropInventoryComponent_PFBAlpha.DinoDropInventoryComponent_PFBAlpha_C",
			"sets": [
				{
					"name": "Origin",
					"weight": 1,
					"qtyScale": { "min": 5, "max": 5, "pow": 1 },
					"entries": [
						{
							"name": "Armor",
							"weight": 1,
							"qty": { "min": 0, "max": 1, "pow": 1 },
							"quality": { "min": 0, "max": 7, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItemArmor_AlphaMetalBoots_C",
								"PrimalItemArmor_AlphaMetalGloves_C",
								"PrimalItemArmor_AlphaMetalHelmet_C",
								"PrimalItemArmor_AlphaMetalPants_C",
								"PrimalItemArmor_AlphaMetalShirt_C"
							]
						},
						{
							"name": "Items",
							"weight": 1,
							"qty": { "min": 5, "max": 10, "pow": 1 },
							"quality": { "min": 0, "max": 0, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItemAmmo_PotentArrowTranq_C",
								"PrimalItemConsumable_PotentNarcotic_C",
								"PrimalItemConsumable_TameHelperx5_C",
								"PrimalItemConsumable_PrimalStimulant_C",
								"PrimalItemConsumable_smallXP_C",
								"PrimalItemResource_AdvancedDartCasing_C"
							]
						},
						{
							"name": "Weapons",
							"weight": 1,
							"qty": { "min": 0, "max": 1, "pow": 1 },
							"quality": { "min": 0, "max": 3, "pow": 1 },
							"forceBP": false,
							"items": [ "PrimalItem_WeaponPrimalPike_C" ]
						},
						{
							"name": "Boss Essence",
							"weight": 1,
							"qty": { "min": 30, "max": 50, "pow": 1 },
							"quality": { "min": 0, "max": 1, "pow": 1 },
							"forceBP": false,
							"items": [ "PrimalItemResource_BossEssence_C" ]
						},
						{
							"name": "Element",
							"weight": 1,
							"qty": { "min": 20, "max": 40, "pow": 1 },
							"quality": { "min": 0, "max": 3, "pow": 1 },
							"forceBP": false,
							"items": [ "PrimalItemResource_Element_C" ]
						},
						{
							"name": "tools",
							"weight": 1,
							"qty": { "min": 0, "max": 2, "pow": 1 },
							"quality": { "min": 1, "max": 4.5, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItem_WeaponMetalPick_C",
								"PrimalItem_WeaponMetalHatchet_C",
								"PrimalItem_WeaponOneShotRifle_C",
								"PrimalItem_WeaponShotgun_C",
								"PrimalItem_WeaponPike_C",
								"PrimalItem_WeaponSword_C",
								"PrimalItemArmor_MetalShield_C",
								"PrimalItem_WeaponCrossbow_C",
								"PrimalItemArmor_MetalHelmet_C",
								"PrimalItemArmor_MetalBoots_C",
								"PrimalItemArmor_MetalGloves_C",
								"PrimalItemArmor_MetalShirt_C",
								"PrimalItemArmor_MetalPants_C"
							]
						}
					]
				}
			]
		},
		{
			"bp": "/Game/Mods/Primal_Fear_Bosses/LootSets/Apex/DinoDropInventoryComponent_PFBApex.DinoDropInventoryComponent_PFBApex_C",
			"sets": [
				{
					"name": "Origin",
					"weight": 1,
					"qtyScale": { "min": 5, "max": 5, "pow": 1 },
					"entries": [
						{
							"name": "Armor",
							"weight": 1,
							"qty": { "min": 1, "max": 1, "pow": 1 },
							"quality": { "min": 1, "max": 7, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItemArmor_ApexMetalBoots_C",
								"PrimalItemArmor_ApexMetalGloves_C",
								"PrimalItemArmor_ApexMetalHelmet_C",
								"PrimalItemArmor_ApexMetalPants_C",
								"PrimalItemArmor_ApexMetalShirt_C"
							]
						},
						{
							"name": "Items",
							"weight": 1,
							"qty": { "min": 4, "max": 10, "pow": 1 },
							"quality": { "min": 0, "max": 0, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItemAmmo_PotentArrowTranq_C",
								"PrimalItemConsumable_PotentNarcotic_C",
								"PrimalItemAmmo_PotentTranqDart_C",
								"PrimalItemConsumable_TameHelperx10_C",
								"PrimalItemConsumable_TameHelperx5_C",
								"PrimalItemConsumable_PrimalStimulant_C",
								"PrimalItemConsumable_smallXP_C",
								"PrimalItemConsumable_mediumXP_C",
								"PrimalItemAmmo_PrimalShotgunBullet_C",
								"PrimalItemResource_AdvancedDartCasing_C"
							]
						},
						{
							"name": "Weapons",
							"weight": 1,
							"qty": { "min": 0, "max": 1, "pow": 1 },
							"quality": { "min": 1, "max": 7, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItem_WeaponPrimalMachinedSniper_Child_C",
								"PrimalItem_WeaponPrimalPike_C",
								"PrimalItem_WeaponMachinedPrimalShotgun_C"
							]
						},
						{
							"name": "Boss Essence",
							"weight": 1,
							"qty": { "min": 50, "max": 70, "pow": 1 },
							"quality": { "min": 0, "max": 1, "pow": 1 },
							"forceBP": true,
							"items": [ "PrimalItemResource_BossEssence_C" ]
						},
						{
							"name": "Element",
							"weight": 1,
							"qty": { "min": 55, "max": 100, "pow": 1 },
							"quality": { "min": 0, "max": 3, "pow": 1 },
							"forceBP": false,
							"items": [ "PrimalItemResource_Element_C" ]
						},
						{
							"name": "tools",
							"weight": 1,
							"qty": { "min": 1, "max": 4, "pow": 1 },
							"quality": { "min": 4.5, "max": 10, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItem_WeaponMetalPick_C",
								"PrimalItem_WeaponMetalHatchet_C",
								"PrimalItem_WeaponOneShotRifle_C",
								"PrimalItem_WeaponRifle_C",
								"PrimalItem_WeaponMachinedSniper_C",
								"PrimalItem_WeaponMachinedShotgun_C",
								"PrimalItem_WeaponShotgun_C",
								"PrimalItem_WeaponPike_C",
								"PrimalItem_WeaponSword_C",
								"PrimalItemArmor_MetalShield_C",
								"PrimalItem_WeaponCrossbow_C",
								"PrimalItem_WeaponCompoundBow_C",
								"PrimalItemArmor_MetalHelmet_C",
								"PrimalItemArmor_MetalBoots_C",
								"PrimalItemArmor_MetalGloves_C",
								"PrimalItemArmor_MetalShirt_C",
								"PrimalItemArmor_MetalPants_C",
								"PrimalItem_WeaponMachinedPistol_C"
							]
						}
					]
				}
			]
		},
		{
			"bp": "/Game/Mods/Primal_Fear_Bosses/LootSets/Chaos/DinoDropInventoryComponent_PFBChaos.DinoDropInventoryComponent_PFBChaos_C",
			"sets": [
				{
					"name": "Origin",
					"weight": 1,
					"qtyScale": { "min": 4, "max": 4, "pow": 1 },
					"entries": [
						{
							"name": "Items",
							"weight": 1,
							"qty": { "min": 15, "max": 25, "pow": 1 },
							"quality": { "min": 0, "max": 0, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItemConsumable_TameHelperx20_C",
								"PrimalItemAmmo_EPrimalCompoundBowArrow_C",
								"PrimalItemAmmo_PrimalFlameCompoundBowArrow_C",
								"PrimalItemAmmo_PrimalCompoundBowArrow_C",
								"PrimalItemAmmo_PrimalShotgunBullet_C",
								"PrimalItemConsumable_largeXP_C",
								"PrimalItemAmmo_PrimalTranqDart_C",
								"PrimalItemAmmo_PrimalPrimalCompoundBowArrow_C"
							]
						},
						{
							"name": "Weapons",
							"weight": 1,
							"qty": { "min": 1, "max": 2, "pow": 1 },
							"quality": { "min": 7, "max": 10, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItem_WeaponPrimalMachinedSniper_Child_C",
								"PrimalItem_WeaponPrimalPike_C",
								"PrimalItem_WeaponPrimalCompoundBow_C",
								"PrimalItem_WeaponMachinedPrimalShotgun_C",
								"PrimalItem_WeaponPrimalRocketLauncher_C"
							]
						},
						{
							"name": "Boss Essence",
							"weight": 1,
							"qty": { "min": 70, "max": 90, "pow": 1 },
							"quality": { "min": 0, "max": 1, "pow": 1 },
							"forceBP": true,
							"items": [ "PrimalItemResource_BossEssence_C" ]
						},
						{
							"name": "Element",
							"weight": 1,
							"qty": { "min": 75, "max": 150, "pow": 1 },
							"quality": { "min": 0, "max": 3, "pow": 1 },
							"forceBP": false,
							"items": [ "PrimalItemResource_Element_C" ]
						}
					]
				}
			]
		},
		{
			"bp": "/Game/Mods/Primal_Fear_Bosses/LootSets/Primal/DinoDropInventoryComponent_PFBPrimal.DinoDropInventoryComponent_PFBPrimal_C",
			"sets": [
				{
					"name": "Origin",
					"weight": 1,
					"qtyScale": { "min": 5, "max": 5, "pow": 1 },
					"entries": [
						{
							"name": "Armor",
							"weight": 1,
							"qty": { "min": 1, "max": 2, "pow": 1 },
							"quality": { "min": 4.5, "max": 10, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItemArmor_PrimalMetalBoots_C",
								"PrimalItemArmor_PrimalMetalGloves_C",
								"PrimalItemArmor_PrimalMetalHelmet_C",
								"PrimalItemArmor_PrimalMetalPants_C",
								"PrimalItemArmor_PrimalMetalShirt_C"
							]
						},
						{
							"name": "Items",
							"weight": 1,
							"qty": { "min": 35, "max": 60, "pow": 1 },
							"quality": { "min": 0, "max": 0, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItemConsumable_PotentNarcotic_C",
								"PrimalItemAmmo_PrimalPotentTranqBullet_C",
								"PrimalItemConsumable_TameHelperx10_C",
								"PrimalItemConsumable_TameHelperx20_C",
								"PrimalItemConsumable_TameHelperx5_C",
								"PrimalItemConsumable_PrimalStimulant_C",
								"PrimalItemConsumable_mediumXP_C",
								"PrimalItemConsumable_largeXP_C",
								"PrimalItemAmmo_PrimalShotgunBullet_C",
								"PrimalItemAmmo_EPrimalCompoundBowArrow_C",
								"PrimalItemAmmo_PrimalFlameCompoundBowArrow_C",
								"PrimalItemAmmo_PrimalCompoundBowArrow_C",
								"PrimalItemAmmo_PotentPrimalCompoundBowArrow_C",
								"PrimalItemConsumable_PrimalHealth_C",
								"PrimalItemResource_AdvancedDartCasing_C",
								"PrimalItemAmmo_PotentTranqDart_C"
							]
						},
						{
							"name": "Weapons",
							"weight": 1,
							"qty": { "min": 1, "max": 2, "pow": 1 },
							"quality": { "min": 6, "max": 10, "pow": 1 },
							"forceBP": false,
							"items": [
								"PrimalItem_WeaponPrimalMachinedSniper_Child_C",
								"PrimalItem_WeaponPrimalPike_C",
								"PrimalItem_WeaponPrimalCompoundBow_C",
