=== PiTi2k5/Obelisk/data/wiki/.schema/species.json
{
	"title": "Species data for the Wiki",
	"type": "object",
	"properties": {
		"version": {
			"title": "Version",
			"description": "Data version of the format <gamemajor>.<gamemajor>.<specificversion>, e.g. '306.83.4740398'",
			"type": "string"
		},
		"format": {
			"title": "Format",
			"description": "Free-form format identifier, changed only when incompatibilities are introduced",
			"type": "string"
		},
		"mod": {
			"title": "Mod info",
			"description": "Source module information",
			"allOf": [
				{
					"$ref": "#/definitions/ModInfo"
				}
			]
		},
		"species": {
			"title": "Species",
			"type": "array",
			"items": {
				"$ref": "#/definitions/Species"
			}
		}
	},
	"required": [
		"version",
		"format",
		"species"
	],
	"additionalProperties": false,
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"ModInfo": {
			"title": "ModInfo",
			"type": "object",
			"properties": {
				"id": {
					"title": "Mod ID",
					"type": "string"
				},
				"tag": {
					"title": "Blueprint tag",
					"description": "Used in place of the mod ID in blueprint paths",
					"type": "string"
				},
				"title": {
					"title": "Mod name",
					"type": "string"
				}
			},
			"required": [
				"id",
				"tag",
				"title"
			]
		},
		"FallingData": {
			"title": "FallingData",
			"type": "object",
			"properties": {
				"dmgMult": {
					"title": "Damage multiplier",
					"type": "number"
				},
				"maxSpeed": {
					"title": "Max speed",
					"type": "number"
				}
			},
			"required": [
				"dmgMult",
				"maxSpeed"
			],
			"additionalProperties": false
		},
		"SpeedData": {
			"title": "SpeedData",
			"type": "object",
			"properties": {
				"base": {
					"title": "Base",
					"type": "number"
				},
				"crouch": {
					"title": "Crouch",
					"type": "number"
				},
				"sprint": {
					"title": "Sprint",
					"type": "number"
				}
			},
			"required": [
				"base"
			]
		},
		"MovementModes": {
			"title": "MovementModes",
			"type": "object",
			"properties": {
				"walk": {
					"$ref": "#/definitions/SpeedData"
				},
				"fly": {
					"$ref": "#/definitions/SpeedData"
				},
				"swim": {
					"$ref": "#/definitions/SpeedData"
				}
			}
		},
		"AttackInfo": {
			"title": "AttackInfo",
			"type": "object",
			"properties": {
				"name": {
					"title": "Name",
					"type": "string"
				},
				"interval": {
					"title": "Interval",
					"type": "number"
				},
				"dmg": {
					"title": "Dmg",
					"type": "integer"
				},
				"radius": {
					"title": "Radius",
					"type": "number"
				},
				"stamina": {
					"title": "Stamina",
					"type": "number"
				},
				"isProjectile": {
					"title": "Isprojectile",
					"default": false,
					"type": "boolean"
				}
			},
			"required": [
				"name",
				"interval",
				"dmg",
				"radius",
				"stamina"
			],
			"additionalProperties": false
		},
		"AttackData": {
			"title": "AttackData",
			"type": "object",
			"properties": {
				"defaultDmg": {
					"title": "Defaultdmg",
					"type": "integer"
				},
				"defaultSwingRadius": {
					"title": "Defaultswingradius",
					"type": "number"
				},
				"attacks": {
					"title": "Attacks",
					"type": "array",
					"items": {
						"$ref": "#/definitions/AttackInfo"
					}
				}
			},
			"additionalProperties": false
		},
		"Species": {
			"title": "Species",
			"type": "object",
			"properties": {
				"name": {
					"title": "Name",
					"description": "Descriptive name",
					"type": "string"
				},
				"blueprintPath": {
					"title": "Full blueprint path",
					"type": "string"
				},
				"dinoNameTag": {
					"title": "Dino name tag",
					"description": "Only known use is saddle compatibility",
					"type": "string"
				},
				"customTag": {
					"title": "Custom tag",
					"type": "string"
				},
				"targetingTeamName": {
					"title": "Targeting team name",
					"description": "Prevent friendly fire with creatures in the same team",
					"type": "string"
				},
				"mass": {
					"title": "Mass",
					"description": "Physics mass, used as a limit in some immobilisation systems",
					"type": "number"
				},
				"dragWeight": {
					"title": "Drag weight",
					"description": "Apparent weight for many game systems including carrying and boss arena entry limits",
					"type": "number"
				},
				"variants": {
					"title": "Variants",
					"description": "List of relevant variant names",
					"default": [],
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"flags": {
					"title": "Flags",
					"description": "Relevant boolean flags that are True for this species",
					"default": [],
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"falling": {
					"$ref": "#/definitions/FallingData"
				},
				"movementW": {
					"title": "Movement (wild)",
					"allOf": [
						{
							"$ref": "#/definitions/MovementModes"
						}
					]
				},
				"movementD": {
					"title": "Movement (domesticated)",
					"allOf": [
						{
							"$ref": "#/definitions/MovementModes"
						}
					]
				},
				"attack": {
					"$ref": "#/definitions/AttackData"
				}
			},
			"required": [
				"blueprintPath"
			],
			"additionalProperties": false
		}
	}
}

=== PiTi2k5/Obelisk/data/wiki/1498206270-SmallDragon/species.json
{
	"version": "305.13.1563727344",
	"format": "1",
	"mod": {
		"id": "1498206270",
		"tag": "SmallDragon",
		"title": "Small Dragons!"
	},
	"species": [
		{
			"name": "Dino Flyer",
			"blueprintPath": "/Game/Mods/SmallDragon/Dino_Character_BP_DivingDragonFlyer.Dino_Character_BP_DivingDragonFlyer_C",
			"dinoNameTag": "Diving Flyer",
			"customTag": "",
			"targetingTeamName": "",
			"mass": 100,
			"dragWeight": 35,
			"flags": [
				"allowFlyerLandedRider",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"isFlyerDino"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 600, "sprint": 900 },
				"fly": { "base": 600 },
				"swim": { "base": 300 }
			},
			"movementD": {
				"walk": { "base": 600, "sprint": 900 },
				"fly": { "base": 600 },
				"swim": { "base": 300 }
			},
			"attack": {
				"defaultDmg": 0,
				"defaultSwingRadius": 90
			}
		},
		{
			"name": "Small Dragon",
			"blueprintPath": "/Game/Mods/SmallDragon/SmallDragon_Character_BP.SmallDragon_Character_BP_C",
			"dinoNameTag": "Small Dragon",
			"customTag": "Small Dragon",
			"targetingTeamName": "Carnivores_High",
			"mass": 1200,
			"dragWeight": 1000,
			"flags": [
				"allowFlyerLandedRider",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"doStepDamage",
				"isBigDino",
				"isCarnivore",
				"isFlyerDino"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 330, "sprint": 990 },
				"fly": { "base": 915, "sprint": 503.3 },
				"swim": { "base": 60 }
			},
			"movementD": {
				"walk": { "base": 552.8, "sprint": 1658.3 },
				"fly": { "base": 1532.6, "sprint": 842.9 },
				"swim": { "base": 100.5 }
			},
			"attack": {
				"defaultDmg": 160,
				"defaultSwingRadius": 1200,
				"attacks": [
					{ "name": "Bite", "interval": 0.75, "dmg": 75, "radius": 1200, "stamina": 30 },
					{ "name": "Flame", "interval": 15, "dmg": 0, "radius": 1200, "stamina": 100 },
					{ "name": "PickUp", "interval": 1, "dmg": 1, "radius": 370, "stamina": 30 },
					{ "name": "WingAttack", "interval": 1, "dmg": 60, "radius": 2000, "stamina": 10 },
					{ "name": "Roar", "interval": 1, "dmg": 0, "radius": 0, "stamina": 10 },
					{ "name": "Swipe", "interval": 0.75, "dmg": 27, "radius": 1200, "stamina": 10 },
					{ "name": "Divebomb", "interval": 2, "dmg": 185, "radius": 2000, "stamina": 30 },
					{ "name": "Sweep", "interval": 1, "dmg": 27, "radius": 750, "stamina": 0 }
				]
			}
		}
	]
}

=== PiTi2k5/Obelisk/data/wiki/1934081600-SoloFarmAnky/species.json
{
	"version": "309.53.1581239136",
	"format": "1",
	"mod": {
		"id": "1934081600",
		"tag": "SoloFarmAnky",
		"title": "Solo Farm Mod"
	},
	"species": [
		{
			"name": "Ankylosaurus",
			"blueprintPath": "/Game/Mods/SoloFarmAnky/SFA_Anky/Ankylo_Character_BP.Ankylo_Character_BP_C",
			"dinoNameTag": "Anky",
			"customTag": "Anky",
			"targetingTeamName": "Herbivores",
			"mass": 300,
			"dragWeight": 160,
			"flags": [
				"allowMountedWeaponry",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 120, "sprint": 264 }
			},
			"movementD": {
				"walk": { "base": 120, "sprint": 264 }
			},
			"attack": {
				"defaultDmg": 50,
				"defaultSwingRadius": 370,
				"attacks": [
					{ "name": "WalkingAndSwimmingTail", "interval": 0.67, "dmg": 50, "radius": 370, "stamina": 0 },
					{ "name": "Bite", "interval": 0.67, "dmg": 30, "radius": 250, "stamina": 0 },
					{ "name": "NotWalkingNotSwimmingTailAttack", "interval": 0.67, "dmg": 50, "radius": 370, "stamina": 0 }
				]
			}
		},
		{
			"name": "Aberrant Ankylosaurus",
			"blueprintPath": "/Game/Mods/SoloFarmAnky/SFA_Anky/Ankylo_Character_BP_Aberrant.Ankylo_Character_BP_Aberrant_C",
			"dinoNameTag": "Anky",
			"customTag": "Anky",
			"targetingTeamName": "Herbivores",
			"mass": 300,
			"dragWeight": 160,
			"flags": [
				"allowMountedWeaponry",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 120, "sprint": 264 }
			},
			"movementD": {
				"walk": { "base": 120, "sprint": 264 }
			},
			"attack": {
				"defaultDmg": 50,
				"defaultSwingRadius": 370,
				"attacks": [
					{ "name": "WalkingAndSwimmingTail", "interval": 0.67, "dmg": 50, "radius": 370, "stamina": 0 },
					{ "name": "Bite", "interval": 0.67, "dmg": 30, "radius": 250, "stamina": 0 },
					{ "name": "NotWalkingNotSwimmingTailAttack", "interval": 0.67, "dmg": 50, "radius": 370, "stamina": 0 }
				]
			}
		}
	]
}

=== PiTi2k5/Obelisk/data/wiki/1633860796-DE_Breedable_RockDrakes/species.json
{
	"version": "309.53.1548344384",
	"format": "1",
	"mod": {
		"id": "1633860796",
		"tag": "DE_Breedable_RockDrakes",
		"title": "Dark Edges Breedable Rock Drakes"
	},
	"species": [
		{
			"name": "Rock Drake",
			"blueprintPath": "/Game/Mods/DE_Breedable_RockDrakes/Dinos/RockDrakes/RockDrake_Character_BP_DE.RockDrake_Character_BP_DE_C",
			"dinoNameTag": "RockDrake",
			"customTag": "RockDrake",
			"targetingTeamName": "Carnivores_High",
			"mass": 345,
			"dragWeight": 425,
			"flags": [
				"allowMountedWeaponry",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"doStepDamage",
				"isCarnivore",
				"preventNeuter"
			],
			"falling": {
				"dmgMult": 10,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 520, "sprint": 1820 },
				"swim": { "base": 480 }
			},
			"movementD": {
				"walk": { "base": 585, "sprint": 2047.5 },
				"swim": { "base": 540 }
			},
			"attack": {
				"defaultDmg": 0,
				"defaultSwingRadius": 600,
				"attacks": [
					{ "name": "Bite", "interval": 0.5, "dmg": 60, "radius": 600, "stamina": 20 },
					{ "name": "Toggle Climbing", "interval": 0, "dmg": 0, "radius": 0, "stamina": 0 },
					{ "name": "Toggle Camo", "interval": 0, "dmg": 0, "radius": 0, "stamina": 0 },
					{ "name": "Pounce_DirectHit", "interval": 0, "dmg": 240, "radius": 0, "stamina": 0 },
					{ "name": "Pounce_AOE", "interval": 0, "dmg": 150, "radius": 0, "stamina": 0 },
					{ "name": "Bite (Climbing)", "interval": 0.5, "dmg": 60, "radius": 900, "stamina": 20 }
				]
			}
		}
	]
}

=== PiTi2k5/Obelisk/data/wiki/1522327484-Additions_Pack/species.json
{
	"version": "305.13.1579616448",
	"format": "1",
	"mod": {
		"id": "1522327484",
		"tag": "Additions_Pack",
		"title": "ARK Additions!"
	},
	"species": [
		{
			"name": "Acrocanthosaurus",
			"blueprintPath": "/Game/Mods/Additions_Pack/Acrocanthosaurus/Dinos/Acrocanthosaurus_Character_BP.Acrocanthosaurus_Character_BP_C",
			"dinoNameTag": "Acro",
			"customTag": "Acro",
			"targetingTeamName": "Carnivores_High",
			"mass": 450,
			"dragWeight": 550,
			"flags": [
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"doStepDamage",
				"isBigDino",
				"isCarnivore"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 520, "sprint": 1144 }
			},
			"movementD": {
				"walk": { "base": 650, "sprint": 1430 }
			},
			"attack": {
				"defaultDmg": 0,
				"defaultSwingRadius": 90,
				"attacks": [
					{ "name": "Bite", "interval": 0.5, "dmg": 55, "radius": 400, "stamina": 0 },
					{ "name": "Shield Stance", "interval": 0, "dmg": 0, "radius": 0, "stamina": 0 },
					{ "name": "Stomp", "interval": 15, "dmg": 95, "radius": 800, "stamina": 7 },
					{ "name": "ShieldBash", "interval": 0, "dmg": 20, "radius": 800, "stamina": 0 },
					{ "name": "Roar", "interval": 0, "dmg": 0, "radius": 0, "stamina": 0 },
					{ "name": "AdrenalineBite", "interval": 2, "dmg": 55, "radius": 400, "stamina": 0 }
				]
			}
		},
		{
			"name": "Archelon",
			"blueprintPath": "/Game/Mods/Additions_Pack/Archelon/Dinos/Archelon_Character_BP.Archelon_Character_BP_C",
			"dinoNameTag": "Archelon",
			"customTag": "Archelon",
			"targetingTeamName": "Carnivores_High",
			"mass": 350,
			"dragWeight": 550,
			"flags": [ "allowMountedWeaponry", "allowRiding", "canBeDragged", "isBigDino" ],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 200, "sprint": 300 }
			},
			"movementD": {
				"walk": { "base": 200, "sprint": 300 }
			},
			"attack": {
				"defaultDmg": 0,
				"defaultSwingRadius": 90,
				"attacks": [ { "name": "None", "interval": 1, "dmg": 25, "radius": 400, "stamina": 0 } ]
			}
		},
		{
			"name": "Brachiosaurus",
			"blueprintPath": "/Game/Mods/Additions_Pack/Brachiosaurus/Dinos/Brachiosaurus_Character_BP.Brachiosaurus_Character_BP_C",
			"dinoNameTag": "AdditionsBrachio",
			"customTag": "AdditionsBrachio",
			"targetingTeamName": "Herbivores_Large",
			"mass": 750,
			"dragWeight": 3000,
			"flags": [
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"doStepDamage",
				"isBigDino"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 287.5, "sprint": 575 }
			},
			"movementD": {
				"walk": { "base": 250, "sprint": 500 }
			},
			"attack": {
				"defaultDmg": 0,
				"defaultSwingRadius": 90,
				"attacks": [
					{ "name": "FrontStomps", "interval": 1.5, "dmg": 110, "radius": 700, "stamina": 30 },
					{ "name": "BackStomps", "interval": 1, "dmg": 95, "radius": 700, "stamina": 20 },
					{ "name": "ChangeStance", "interval": 0, "dmg": 0, "radius": 100, "stamina": 15 },
					{ "name": "Bellow", "interval": 0, "dmg": 1, "radius": 1500, "stamina": 150 },
					{ "name": "MegaStomp", "interval": 0, "dmg": 2000, "radius": 1700, "stamina": 0 }
				]
			}
		},
		{
			"name": "Aberrant Brachiosaurus",
			"blueprintPath": "/Game/Mods/Additions_Pack/Brachiosaurus/Dinos/Brachiosaurus_Character_BP_Aberrant.Brachiosaurus_Character_BP_Aberrant_C",
			"dinoNameTag": "AdditionsBrachio",
			"customTag": "AdditionsBrachio",
			"targetingTeamName": "Herbivores_Large",
			"mass": 750,
			"dragWeight": 3000,
			"flags": [
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"doStepDamage",
				"isBigDino"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 287.5, "sprint": 575 }
			},
			"movementD": {
				"walk": { "base": 250, "sprint": 500 }
			},
			"attack": {
				"defaultDmg": 0,
				"defaultSwingRadius": 90,
				"attacks": [
					{ "name": "FrontStomps", "interval": 1.5, "dmg": 110, "radius": 700, "stamina": 30 },
					{ "name": "BackStomps", "interval": 1, "dmg": 95, "radius": 700, "stamina": 20 },
					{ "name": "ChangeStance", "interval": 0, "dmg": 0, "radius": 100, "stamina": 15 },
					{ "name": "Bellow", "interval": 0, "dmg": 1, "radius": 1500, "stamina": 150 },
					{ "name": "MegaStomp", "interval": 0, "dmg": 2000, "radius": 1700, "stamina": 0 }
				]
			}
		},
		{
			"name": "Deinosuchus",
			"blueprintPath": "/Game/Mods/Additions_Pack/Deinosuchus/Dino/Deinosuchus_Character_BP.Deinosuchus_Character_BP_C",
			"dinoNameTag": "Deino",
			"customTag": "Deino",
			"targetingTeamName": "Carnivores_High",
			"mass": 250,
			"dragWeight": 300,
			"flags": [
				"allowMountedWeaponry",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"isAmphibious",
				"isBigDino",
				"isCarnivore"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 202.5, "sprint": 303.8 }
			},
			"movementD": {
				"walk": { "base": 262.5, "sprint": 393.8 }
			},
			"attack": {
				"defaultDmg": 60,
				"defaultSwingRadius": 200,
				"attacks": [
					{ "name": "Bite", "interval": 1, "dmg": 50, "radius": 350, "stamina": 0 },
					{ "name": "GashBite", "interval": 5, "dmg": 70, "radius": 350, "stamina": 20 },
					{ "name": "TailSwing", "interval": 0, "dmg": 5, "radius": 400, "stamina": 5 },
					{ "name": "Bite", "interval": 1, "dmg": 50, "radius": 350, "stamina": 0 },
					{ "name": "Right-Bite", "interval": 1, "dmg": 50, "radius": 350, "stamina": 0 }
				]
			}
		},
		{
			"name": "Aberrant Deinosuchus",
			"blueprintPath": "/Game/Mods/Additions_Pack/Deinosuchus/Dino/Deinosuchus_Character_BP_Aberrant.Deinosuchus_Character_BP_Aberrant_C",
			"dinoNameTag": "Deino",
			"customTag": "Deino",
			"targetingTeamName": "Carnivores_High",
			"mass": 250,
			"dragWeight": 300,
			"flags": [
				"allowMountedWeaponry",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"isAmphibious",
				"isBigDino",
				"isCarnivore"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 202.5, "sprint": 303.8 }
			},
			"movementD": {
				"walk": { "base": 262.5, "sprint": 393.8 }
			},
			"attack": {
				"defaultDmg": 60,
				"defaultSwingRadius": 200,
				"attacks": [
					{ "name": "Bite", "interval": 1, "dmg": 50, "radius": 350, "stamina": 0 },
					{ "name": "GashBite", "interval": 5, "dmg": 70, "radius": 350, "stamina": 20 },
					{ "name": "TailSwing", "interval": 0, "dmg": 5, "radius": 400, "stamina": 5 },
					{ "name": "Bite", "interval": 1, "dmg": 50, "radius": 350, "stamina": 0 },
					{ "name": "Right-Bite", "interval": 1, "dmg": 50, "radius": 350, "stamina": 0 }
				]
			}
		},
		{
			"name": "Xiphactinus",
			"blueprintPath": "/Game/Mods/Additions_Pack/Xiphactinus/Dino/Xiph_Character_BP.Xiph_Character_BP_C",
			"dinoNameTag": "Xiph",
			"customTag": "Xiph",
			"targetingTeamName": "Carnivores_Large",
			"mass": 200,
			"dragWeight": 250,
			"flags": [
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"isCarnivore",
				"isWaterDino"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"swim": { "base": 675 }
			},
			"movementD": {
				"swim": { "base": 1346.4 }
			},
			"attack": {
				"defaultDmg": 20,
				"defaultSwingRadius": 200,
				"attacks": [ { "name": "Bite", "interval": 0.55, "dmg": 23, "radius": 200, "stamina": 0 } ]
			}
		}
	]
}

=== PiTi2k5/Obelisk/data/wiki/1136390783-PhoenixBreeding/species.json
{
	"$schema": "../.schema/species.json",
	"version": "310.77.1505566966",
	"format": "1",
	"mod": {
		"id": "1136390783",
		"tag": "PhoenixBreeding",
		"title": "Phoenix Breeding"
	},
	"species": [
		{
			"name": "Phoenix",
			"blueprintPath": "/Game/Mods/PhoenixBreeding/Phoenix/Phoenix_Character_BP_Breedable.Phoenix_Character_BP_Breedable_C",
			"dinoNameTag": "Phoenix",
			"customTag": "Phoenix",
			"targetingTeamName": "Herbivores",
			"mass": 190,
			"dragWeight": 35,
			"flags": [
				"allowRiding",
				"canBeDragged",
				"canDrag",
				"isCarnivore",
				"isFlyerDino"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 364, "sprint": 637 },
				"fly": { "base": 840 },
				"swim": { "base": 420 }
			},
			"movementD": {
				"walk": { "base": 520, "sprint": 910 },
				"fly": { "base": 1200 },
				"swim": { "base": 600 }
			},
			"attack": {
				"defaultDmg": 14,
				"defaultSwingRadius": 185,
				"attacks": [
					{ "name": "Attack Bite", "interval": 0.6, "dmg": 14, "radius": 350, "stamina": 0 },
					{
						"name": "Fireball (Rider)", "interval": 4, "dmg": 0, "radius": 0, "stamina": 75,
						"isProjectile": true
					},
					{ "name": "Melee Rake", "interval": 1, "dmg": 23, "radius": 350, "stamina": 0 }
				]
			}
		}
	]
}

=== PiTi2k5/Obelisk/data/wiki/1268749723-ShadCore/species.json
{
	"version": "305.13.1515901388",
	"format": "1",
	"mod": {
		"id": "1268749723",
		"tag": "ShadCore",
		"title": "Origin Manticore"
	},
	"species": [
		{
			"name": "Origin Manticore",
			"blueprintPath": "/Game/Mods/ShadCore/ShadCore_Character_bp.ShadCore_Character_bp_C",
			"dinoNameTag": "Manticore",
			"customTag": "Shadcore",
			"targetingTeamName": "Carnivores_High",
			"mass": 400,
			"dragWeight": 550,
			"flags": [
				"allowFlyerLandedRider",
				"allowMountedWeaponry",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"flyerAllowRidingInCaves",
				"isBigDino",
				"isCarnivore",
				"isFlyerDino"
			],
			"falling": {
				"dmgMult": 80,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 350, "sprint": 1750 },
				"fly": { "base": 700, "sprint": 560 },
				"swim": { "base": 300 }
			},
			"movementD": {
				"walk": { "base": 350, "sprint": 1750 },
				"fly": { "base": 700, "sprint": 560 },
				"swim": { "base": 300 }
			},
			"attack": {
				"defaultDmg": 45,
				"defaultSwingRadius": 300,
				"attacks": [
					{ "name": "BiteNomFury", "interval": 0.4, "dmg": 50, "radius": 280, "stamina": 0 },
					{ "name": "BiteNomFury", "interval": 5, "dmg": 80, "radius": 1600, "stamina": 500 },
					{ "name": "BiteNomFury", "interval": 0.4, "dmg": 46, "radius": 280, "stamina": 0 },
					{ "name": "BiteNomFury", "interval": 1, "dmg": 53, "radius": 340, "stamina": 0 },
					{ "name": "BiteNomFury", "interval": 0, "dmg": 0, "radius": 0, "stamina": 0 },
					{ "name": "BiteNomFury", "interval": 0, "dmg": 50, "radius": 300, "stamina": 0 }
				]
			}
		}
	]
}

=== PiTi2k5/Obelisk/data/wiki/1270132511-GiantGlowpets/species.json
{
	"version": "309.53.1519946967",
	"format": "1",
	"mod": {
		"id": "1270132511",
		"tag": "GiantGlowpets",
		"title": "Rideable Glowpets"
	},
	"species": [
		{
			"name": "Giant Featherlight",
			"blueprintPath": "/Game/Mods/GiantGlowpets/LanternBird/LanternBird_Character_BP_Giant.LanternBird_Character_BP_Giant_C",
			"dinoNameTag": "RideableLanternBird",
			"customTag": "RideableLanternBird",
			"targetingTeamName": "Herbivores",
			"mass": 80,
			"dragWeight": 100,
			"flags": [
				"allowFlyerLandedRider",
				"allowMountedWeaponry",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"flyerAllowRidingInCaves",
				"isFlyerDino"
			],
			"falling": {
				"dmgMult": 60,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 600, "sprint": 900 },
				"fly": { "base": 600 },
				"swim": { "base": 300 }
			},
			"movementD": {
				"walk": { "base": 600, "sprint": 900 },
				"fly": { "base": 600 },
				"swim": { "base": 300 }
			},
			"attack": {
				"defaultDmg": 36,
				"defaultSwingRadius": 350,
				"attacks": [
					{ "name": "BiteAttack", "interval": 0.6, "dmg": 36, "radius": 210, "stamina": 10 },
					{ "name": "BiteAttack", "interval": 0.6, "dmg": 74, "radius": 210, "stamina": 30 },
					{ "name": "SpeedBuff", "interval": 120, "dmg": 1, "radius": 1, "stamina": 100 }
				]
			}
		},
		{
			"name": "Giant Shinehorn",
			"blueprintPath": "/Game/Mods/GiantGlowpets/LanternGoat/LanternGoat_Character_BP_Giant.LanternGoat_Character_BP_Giant_C",
			"dinoNameTag": "RideableLanternGoat",
			"customTag": "RideableLanternGoat",
			"targetingTeamName": "Herbivores_Medium_Aggressive",
			"mass": 80,
			"dragWeight": 120,
			"flags": [ "allowMountedWeaponry", "allowRiding", "canBeDragged", "canBeTorpid" ],
			"falling": {
				"dmgMult": 60,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 399, "sprint": 598.5 },
				"swim": { "base": 300 }
			},
			"movementD": {
				"walk": { "base": 399, "sprint": 598.5 },
				"swim": { "base": 300 }
			},
			"attack": {
				"defaultDmg": 30,
				"defaultSwingRadius": 125,
				"attacks": [
					{ "name": "Melee", "interval": 0.4, "dmg": 30, "radius": 110, "stamina": 15 },
					{ "name": "Melee", "interval": 0.4, "dmg": 90, "radius": 110, "stamina": 30 }
				]
			}
		},
		{
			"name": "Giant Glowtail",
			"blueprintPath": "/Game/Mods/GiantGlowpets/LanternLizard/LanternLizard_Character_BP_Giant.LanternLizard_Character_BP_Giant_C",
			"dinoNameTag": "RideableLanternLizard",
			"customTag": "RideableLanternLizard",
			"targetingTeamName": "Herbivores_Medium_Aggressive",
			"mass": 80,
			"dragWeight": 160,
			"flags": [
				"allowMountedWeaponry",
				"allowRiding",
				"canBeDragged",
				"canBeTorpid",
				"canDrag",
				"flyerAllowRidingInCaves"
			],
			"falling": {
				"dmgMult": 10,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 600, "sprint": 900 },
				"swim": { "base": 600 }
			},
			"movementD": {
				"walk": { "base": 600, "sprint": 900 },
				"swim": { "base": 600 }
			},
			"attack": {
				"defaultDmg": 35,
				"defaultSwingRadius": 110,
				"attacks": [
					{ "name": "Melee", "interval": 0.5, "dmg": 60, "radius": 140, "stamina": 15 },
					{ "name": "Tongue", "interval": 10, "dmg": 6, "radius": 360, "stamina": 30 },
					{
						"name": "Spit", "interval": 12, "dmg": 0, "radius": 720, "stamina": 45,
						"isProjectile": true
					}
				]
			}
		},
		{
			"name": "Giant Bulbdog",
			"blueprintPath": "/Game/Mods/GiantGlowpets/LanternPug/LanternPug_Character_BP_Giant.LanternPug_Character_BP_Giant_C",
			"dinoNameTag": "RideablePug",
			"customTag": "RideableLanternPug",
			"targetingTeamName": "Herbivores_Medium_Aggressive",
			"mass": 95,
			"dragWeight": 145,
			"flags": [ "allowMountedWeaponry", "allowRiding", "canBeDragged", "canBeTorpid" ],
			"falling": {
				"dmgMult": 60,
				"maxSpeed": 1550
			},
			"movementW": {
				"walk": { "base": 420, "sprint": 630 },
				"swim": { "base": 300 }
			},
			"movementD": {
				"walk": { "base": 420, "sprint": 630 },
				"swim": { "base": 300 }
			},
			"attack": {
				"defaultDmg": 60,
				"defaultSwingRadius": 142,
				"attacks": [
					{ "name": "Melee", "interval": 0.4, "dmg": 60, "radius": 142, "stamina": 20 },
					{ "name": "Melee2", "interval": 0.8, "dmg": 30, "radius": 95, "stamina": 40 },
					{ "name": "AOEBuff", "interval": 120, "dmg": 1, "radius": 1, "stamina": 100 }
				]
			}
		}
	]
}
